apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: client-profile-gated
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: client-profile-gated
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_repository_name
    value: "trp-gitops-canary"

  build:
    env:
    - name: BP_JVM_VERSION
      value: "18"
  source:
    git:
      url: https://gitlab.eng.vmware.com/vmware-navigator-practice/tooling/client-profile.git
      ref:
        branch: main